### ISSUE TITLE
whichPolygon is not defined

### ISSUE THREAD

**Issue by MinhduongUNO** [mapbox/which-polygon#8]
Hello,

I was trying to incorporate "whichpolygon" into my Javascript to test it

var geojson = require('./countries.json');
var query = whichPolygon(geojson);
query([30.5, 50.5]).admin;

but it kept telling me that it was not defined. I am afraid that I didn't find anything on this GitHub page that could explain how I could fix that. Appreciate it if you could help me 

Thank you

**Comment by mourner** [comment]
Perhaps you forgot to do `var whichPolygon = require('which-polygon');`?
